--Tabela 1 - Model Acces
CREATE TABLE acces ( 
    MOTOR VARCHAR2(200),
    PRET_MOTOR NUMBER(10),
    DESIGN_EXTERIOR VARCHAR2(200),
    PRET_DE NUMBER(10),
    DESIGN_INTERIOR VARCHAR2(200),
    PRET_DI NUMBER(10),
    ECHIPAMENTE VARCHAR2(200),
    PRET_ECHIPAMENTE NUMBER(10)
);

--Tabela 2 - Model Ambiance
CREATE TABLE ambiance ( 
    MOTOR VARCHAR2(200),
    PRET_MOTOR NUMBER(10),
    DESIGN_EXTERIOR VARCHAR2(200),
    PRET_DE NUMBER(10),
    DESIGN_INTERIOR VARCHAR2(200),
    PRET_DI NUMBER(10),
    ECHIPAMENTE VARCHAR2(200),
    PRET_ECHIPAMENTE NUMBER(10)
);

--Tabela 3 - Model Seria Limitata Plus
CREATE TABLE seria_limitata_plus ( 
    MOTOR VARCHAR2(200),
    PRET_MOTOR NUMBER(10),
    DESIGN_EXTERIOR VARCHAR2(200),
    PRET_DE NUMBER(10),
    DESIGN_INTERIOR VARCHAR2(200),
    PRET_DI NUMBER(10),
    ECHIPAMENTE VARCHAR2(200),
    PRET_ECHIPAMENTE NUMBER(10)
);

--Tabela 4 - Model Laureate
CREATE TABLE laureate ( 
    MOTOR VARCHAR2(200),
    PRET_MOTOR NUMBER(10),
    DESIGN_EXTERIOR VARCHAR2(200),
    PRET_DE NUMBER(10),
    DESIGN_INTERIOR VARCHAR2(200),
    PRET_DI NUMBER(10),
    ECHIPAMENTE VARCHAR2(200),
    PRET_ECHIPAMENTE NUMBER(10)
);

--Tabela 5 - Model Stepway
CREATE TABLE stepway ( 
    MOTOR VARCHAR2(200),
    PRET_MOTOR NUMBER(10),
    DESIGN_EXTERIOR VARCHAR2(200),
    PRET_DE NUMBER(10),
    DESIGN_INTERIOR VARCHAR2(200),
    PRET_DI NUMBER(10),
    ECHIPAMENTE VARCHAR2(200),
    PRET_ECHIPAMENTE NUMBER(10)
);

--Tabela 6 - Model Prestige
CREATE TABLE prestige ( 
    MOTOR VARCHAR2(200),
    PRET_MOTOR NUMBER(10),
    DESIGN_EXTERIOR VARCHAR2(200),
    PRET_DE NUMBER(10),
    DESIGN_INTERIOR VARCHAR2(200),
    PRET_DI NUMBER(10),
    ECHIPAMENTE VARCHAR2(200),
    PRET_ECHIPAMENTE NUMBER(10)
);

--Tabela 7 - Model SL Prestige Plus
CREATE TABLE sl_prestige_plus ( 
    MOTOR VARCHAR2(200),
    PRET_MOTOR NUMBER(10),
    DESIGN_EXTERIOR VARCHAR2(200),
    PRET_DE NUMBER(10),
    DESIGN_INTERIOR VARCHAR2(200),
    PRET_DI NUMBER(10),
    ECHIPAMENTE VARCHAR2(200),
    PRET_ECHIPAMENTE NUMBER(10)
);

--Tabela 8 - Model SL Blue Line
CREATE TABLE sl_blue_line ( 
    MOTOR VARCHAR2(200),
    PRET_MOTOR NUMBER(10),
    DESIGN_EXTERIOR VARCHAR2(200),
    PRET_DE NUMBER(10),
    DESIGN_INTERIOR VARCHAR2(200),
    PRET_DI NUMBER(10),
    ECHIPAMENTE VARCHAR2(200),
    PRET_ECHIPAMENTE NUMBER(10)
);