--Insert pentru tabela ACCES
INSERT INTO ACCES(MOTOR, PRET_MOTOR) VALUES('SCe 73 Benzina 5+1 (Manuala)', 7630);

INSERT INTO ACCES(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLANC GLACIER', 0);
INSERT INTO ACCES(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU NAVY', 0);
INSERT INTO ACCES(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de otel 15" cu capace complete Groomy', 0);

INSERT INTO ACCES(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie "Kapia" si plansa de bord "Carbon Foncé"', 0);


--Insert pentru tabela AMBIANCE
INSERT INTO AMBIANCE(MOTOR, PRET_MOTOR) VALUES('SCe 73 Benzina 5+1 (Manuala)', 8700);
INSERT INTO AMBIANCE(MOTOR, PRET_MOTOR) VALUES('TCe 100 GPL Benzina + GPL 5+1 (Manuala)', 9950);
INSERT INTO AMBIANCE(MOTOR, PRET_MOTOR) VALUES('TCe 90 Benzina 5+1 (Manuala)', 9650);
INSERT INTO AMBIANCE(MOTOR, PRET_MOTOR) VALUES('dCi 75 Diesel 5+1 (Manuala)', 10850);

INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLANC GLACIER', 0);
INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU NAVY', 0);
INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare ROUGE FUSION', 340);
INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS HIGHLAND', 340);
INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS COMETE', 340);
INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BEIGE DUNE', 340);
INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BRUN VISON', 340);
INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare NOIR NACRE', 340);
INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de otel 15" cu capace complete Groomy', 0);
INSERT INTO AMBIANCE(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de aluminiu 15" Chamade', 250);

INSERT INTO AMBIANCE(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie "Kapia" si plansa de bord "Carbon Foncé"', 0);

INSERT INTO AMBIANCE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Aer conditionat', 760);
INSERT INTO AMBIANCE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Media Nav: Sistem de navigatie si multimedia cu ecran tactil 7"', 300);
INSERT INTO AMBIANCE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Bancheta spate rabatabila si fractionabila 1/3 si 2/3', 100);
INSERT INTO AMBIANCE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Proiectoare de ceata', 100);
INSERT INTO AMBIANCE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Radio CD 2DIN 4x15W MP3 cu satelit de comanda pe volan, priza Jack, USB, Bluetooth', 20);


--Insert pentru tabela SERIA_LIMITATA_PLUS
INSERT INTO SERIA_LIMITATA_PLUS(MOTOR, PRET_MOTOR) VALUES('SCe 73 Benzina 5+1 (Manuala)', 8610);
INSERT INTO SERIA_LIMITATA_PLUS(MOTOR, PRET_MOTOR) VALUES('TCe 100 GPL Benzina + GPL 5+1 (Manuala)', 9900);
INSERT INTO SERIA_LIMITATA_PLUS(MOTOR, PRET_MOTOR) VALUES('TCe 90 Benzina 5+1 (Manuala)', 9600);
INSERT INTO SERIA_LIMITATA_PLUS(MOTOR, PRET_MOTOR) VALUES('dCi 75 Diesel 5+1 (Manuala)', 10800);

INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLANC GLACIER', 0);
INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU NAVY', 0);
INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare ROUGE FUSION', 340);
INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS HIGHLAND', 340);
INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS COMETE', 340);
INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BEIGE DUNE', 340);
INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BRUN VISON', 340);
INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare NOIR NACRE', 340);
INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de otel 15" cu capace complete Groomy', 0);
INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de aluminiu 15" Chamade', 250);

INSERT INTO SERIA_LIMITATA_PLUS(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie "Kapia" si plansa de bord "Carbon Foncé"', 0);

INSERT INTO SERIA_LIMITATA_PLUS(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Media Nav: Sistem de navigatie si multimedia cu ecran tactil 7"', 300);
INSERT INTO SERIA_LIMITATA_PLUS(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Bancheta spate rabatabila si fractionabila 1/3 si 2/3', 100);
INSERT INTO SERIA_LIMITATA_PLUS(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Radio CD 2DIN 4x15W MP3 cu satelit de comanda pe volan, priza Jack, USB, Bluetooth', 20);


--Insert pentru tabela LAUREATE
INSERT INTO LAUREATE(MOTOR, PRET_MOTOR) VALUES('SCe 73 Benzina 5+1 (Manuala)', 9600);
INSERT INTO LAUREATE(MOTOR, PRET_MOTOR) VALUES('TCe 100 GPL Benzina + GPL 5+1 (Manuala)', 11000);
INSERT INTO LAUREATE(MOTOR, PRET_MOTOR) VALUES('TCe 90 Benzina 5+1 (Manuala)', 10700);
INSERT INTO LAUREATE(MOTOR, PRET_MOTOR) VALUES('dCi 75 Diesel 5+1 (Manuala)', 11900);
INSERT INTO LAUREATE(MOTOR, PRET_MOTOR) VALUES('TCe 90 Easy-R Benzina 5+1 (Automata)', 11200);
INSERT INTO LAUREATE(MOTOR, PRET_MOTOR) VALUES('dCi 95 Diesel 5+1 (Manuala)', 12500);

INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLANC GLACIER', 0);
INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU NAVY', 0);
INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare ROUGE FUSION', 340);
INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS HIGHLAND', 340);
INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS COMETE', 340);
INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BEIGE DUNE', 340);
INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BRUN VISON', 340);
INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare NOIR NACRE', 340);
INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de otel 15" cu capace complete Popster', 0);
INSERT INTO LAUREATE(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de aluminiu 15" Chamade', 0);

INSERT INTO LAUREATE(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie din piele "Riviera Carbon Fonce"', 600);
INSERT INTO LAUREATE(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie "Kapia" si plansa de bord "Carbon Fonce"', 0);

INSERT INTO LAUREATE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Media Nav: Sistem de navigatie si multimedia cu ecran tactil 7"', 300);
INSERT INTO LAUREATE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Pack Look1', 350);
INSERT INTO LAUREATE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Pack Securite', 250);
INSERT INTO LAUREATE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Cruise control"', 150);
INSERT INTO LAUREATE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Cotiera centrala fata, integrata in spatarul scanului sofer si rabatabila', 100);
INSERT INTO LAUREATE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Asistenta la parcarea cu spatele (senzori acustici)', 150);
INSERT INTO LAUREATE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Radio CD 2DIN 4x15W MP3 cu satelit de comanda pe volan, priza Jack, USB, Bluetooth', 20);


--Insert pentru tabela STEPWAY
INSERT INTO STEPWAY(MOTOR, PRET_MOTOR) VALUES('TCe 100 GPL Benzina + GPL 5+1 (Manuala)', 10750);
INSERT INTO STEPWAY(MOTOR, PRET_MOTOR) VALUES('TCe 90 Benzina 5+1 (Manuala)', 10450);
INSERT INTO STEPWAY(MOTOR, PRET_MOTOR) VALUES('dCi 75 Diesel 5+1 (Manuala)', 11650);
INSERT INTO STEPWAY(MOTOR, PRET_MOTOR) VALUES('dCi 95 Diesel 5+1 (Manuala)', 12250);

INSERT INTO STEPWAY(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU AZURITE', 0);
INSERT INTO STEPWAY(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS COMETE', 0);
INSERT INTO STEPWAY(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de otel 15" cu capace complete Popster', 0);
INSERT INTO STEPWAY(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de aluminiu 15" Stepway', 350);

INSERT INTO STEPWAY(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie din piele "Riviera Carbon Fonce"', 600);
INSERT INTO STEPWAY(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie "Kapia" si plansa de bord "Carbon Fonce"', 0);

INSERT INTO STEPWAY(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Pachet special', 300);
INSERT INTO STEPWAY(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Geamuri electrice spate (comenzi pe portiere usi spate si consola centrala)', 100);
INSERT INTO STEPWAY(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Aer conditionat cu reglare automata', 200);
INSERT INTO STEPWAY(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Cotiera centrala fata, integrata in spatarul scanului sofer si rabatabila', 100);
INSERT INTO STEPWAY(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Camera video pentru marsarier', 100);


--Insert pentru tabela PRESTIGE
INSERT INTO PRESTIGE(MOTOR, PRET_MOTOR) VALUES('TCe 90 Benzina 5+1 (Manuala)', 11300);
INSERT INTO PRESTIGE(MOTOR, PRET_MOTOR) VALUES('TCe 90 Easy-R Benzina 5+1 (Automata)', 11800);
INSERT INTO PRESTIGE(MOTOR, PRET_MOTOR) VALUES('dCi 75 Diesel 5+1 (Manuala)', 12500);
INSERT INTO PRESTIGE(MOTOR, PRET_MOTOR) VALUES('dCi 95 Diesel 5+1 (Manuala)', 13100);

INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLANC GLACIER', 0);
INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU NAVY', 0);
INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU IRON', 340);
INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare ROUGE FUSION', 340);
INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS HIGHLAND', 340);
INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS COMETE', 340);
INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BEIGE DUNE', 340);
INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BRUN VISON', 340);
INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare NOIR NACRE', 340);
INSERT INTO PRESTIGE(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de otel structurale 16" cu capace Genea Dark Metal', 0);

INSERT INTO PRESTIGE(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie din piele "Riviera Carbon Fonce"', 600);
INSERT INTO PRESTIGE(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie "Kapia" si plansa de bord "Carbon Fonce"', 0);

INSERT INTO PRESTIGE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Pack Securite', 250);
INSERT INTO PRESTIGE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Media Nav: Sistem de navigatie si multimedia cu ecran tactil 7"', 300);
INSERT INTO PRESTIGE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Cruise control', 150);
INSERT INTO PRESTIGE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Cotiera centrala fata, integrata in spatarul scanului sofer si rabatabila', 100);
INSERT INTO PRESTIGE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Camera video pentru marsarier', 100);
INSERT INTO PRESTIGE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Radio CD 2DIN 4x15W MP3 cu satelit de comanda pe volan, priza Jack, USB, Bluetooth', 20);

--Insert pentru tabela SL_PRESTIGE_PLUS
INSERT INTO SL_PRESTIGE_PLUS(MOTOR, PRET_MOTOR) VALUES('TCe 90 Benzina 5+1 (Manuala)', 10800);
INSERT INTO SL_PRESTIGE_PLUS(MOTOR, PRET_MOTOR) VALUES('dCi 75 Diesel 5+1 (Manuala)', 12000);
INSERT INTO SL_PRESTIGE_PLUS(MOTOR, PRET_MOTOR) VALUES('dCi 95 Diesel 5+1 (Manuala)', 12600);

INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLANC GLACIER', 0);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU NAVY', 0);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU IRON', 340);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare ROUGE FUSION', 340);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS HIGHLAND', 340);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS COMETE', 340);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BEIGE DUNE', 340);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BRUN VISON', 340);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare NOIR NACRE', 340);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante de otel structurale 16" cu capace Genea Dark Metal', 0);

INSERT INTO SL_PRESTIGE_PLUS(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie din piele "Riviera Carbon Fonce"', 600);
INSERT INTO SL_PRESTIGE_PLUS(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie "Kapia" si plansa de bord "Carbon Fonce"', 0);

INSERT INTO SL_PRESTIGE_PLUS(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Volan imbracat in piele', 100);
INSERT INTO SL_PRESTIGE_PLUS(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Pachet Harti(include Media Nav)', 100);
INSERT INTO SL_PRESTIGE_PLUS(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Cotiera centrala fata, integrata in spatarul scanului sofer si rabatabila', 100);
INSERT INTO SL_PRESTIGE_PLUS(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Camera video pentru marsarier', 100);


--Insert pentru tabela SL_BLUE_LINE
INSERT INTO SL_BLUE_LINE(MOTOR, PRET_MOTOR) VALUES('SCe 73 Benzina 5+1 (Manuala)', 9760);
INSERT INTO SL_BLUE_LINE(MOTOR, PRET_MOTOR) VALUES('TCe 100 GPL Benzina + GPL 5+1 (Manuala)', 11050);
INSERT INTO SL_BLUE_LINE(MOTOR, PRET_MOTOR) VALUES('TCe 90 Benzina 5+1 (Manuala)', 10750);
INSERT INTO SL_BLUE_LINE(MOTOR, PRET_MOTOR) VALUES('TCe 90 Easy-R Benzina 5+1 (Automata)', 11250);
INSERT INTO SL_BLUE_LINE(MOTOR, PRET_MOTOR) VALUES('dCi 95 Diesel 5+1 (Manuala)', 12550);

INSERT INTO SL_BLUE_LINE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLANC GLACIER', 0);
INSERT INTO SL_BLUE_LINE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare BLEU IRON', 340);
INSERT INTO SL_BLUE_LINE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS HIGHLAND', 340);
INSERT INTO SL_BLUE_LINE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare GRIS COMETE', 340);
INSERT INTO SL_BLUE_LINE(DESIGN_EXTERIOR, PRET_DE) VALUES('Culoare NOIR NACRE', 340);
INSERT INTO SL_BLUE_LINE(DESIGN_EXTERIOR, PRET_DE) VALUES('Jante otel 16" design Expression', 0);

INSERT INTO SL_BLUE_LINE(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie din piele "Riviera Carbon Fonce"', 600);
INSERT INTO SL_BLUE_LINE(DESIGN_INTERIOR, PRET_DI) VALUES('Tapiterie "Kapia" si plansa de bord "Carbon Fonce"', 0);

INSERT INTO SL_BLUE_LINE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Volan imbracat in piele', 100);
INSERT INTO SL_BLUE_LINE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Pachet Harti(include Media Nav)', 100);
INSERT INTO SL_BLUE_LINE(ECHIPAMENTE, PRET_ECHIPAMENTE) VALUES('Cotiera centrala fata, integrata in spatarul scanului sofer si rabatabila', 100);

